Homework 2/HelpDesk/Models/EmployeeViewModel.cs
using HelpDesk.Enums;

namespace HelpDesk.Models
{
	public class EmployeeViewModel
	{
		public int Id { get; set; }
		public string? FirstName { get; set; }
		public string? LastName { get; set; }

		public Post Post { get; set; }
		public string? Skills { get; set; }

		public string FullName
		{
			get
			{
				if (string.IsNullOrWhiteSpace(LastName))
				{
					return FirstName;
				}
				return $"{FirstName} {LastName}";
			}
		}
	}
}

Homework 2/HelpDesk/Models/ErrorViewModel.cs
namespace HelpDesk.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Homework 2/HelpDesk/Controllers/EmployeeController.cs
using HelpDesk.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace HelpDesk.Controllers
{
    public class EmployeeController : Controller
    {

        static List<EmployeeViewModel> Employees = new List<EmployeeViewModel>();

        // GET: EmployeeController
        public ActionResult Index()
        {
            return View(Employees);
        }

        // GET: EmployeeController/Details/5
        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound("Empty id supplied!");
            }

            try
            {
                var employee = Employees[id.Value];
                return View(employee);
            }
            catch
            {
				return NotFound("No such record found!");
			}
        }

        // GET: EmployeeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmployeeController/Create
        //Adding an Employee to List
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeViewModel employee)
        {
            try
            {
                employee.Id = Employees.Count;
                Employees.Add(employee);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployeeController/Edit/5
        public ActionResult Edit(int? id)
        {
			if (!id.HasValue)
			{
				return NotFound("Empty id supplied!");
			}

            try
            {
                var employee = Employees[id.Value];
                return View(employee);
            }
            catch
            {
				return NotFound("No such record found!");
			}
        }

        // POST: EmployeeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, EmployeeViewModel employee)
        {
            try
            {
                Employees[id] = employee;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

		// GET: EmployeeController/Delete/5
		[HttpGet]
		public ActionResult Delete(int? id)
		{
			if (!id.HasValue)
			{
				return NotFound("Empty id supplied!");
			}
            try
            {
                var employee = Employees[id.Value];

                return View(employee);
            }
            catch
            {
				return NotFound("No such record found!");
			}
		}

		// POST: EmployeeController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int? id, EmployeeViewModel employee)
		{
            try
            {
                employee = Employees[id.Value];
                Employees.Remove(employee);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
				return NotFound("No such record found!");
			}
		}

	}
}

Homework 2/HelpDesk/Controllers/HomeController.cs
using HelpDesk.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HelpDesk.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Homework 2/HelpDesk/Views/Employee/Create.cshtml
@model HelpDesk.Models.EmployeeViewModel
@using HelpDesk.Controllers
@using HelpDesk.Enums
@using System.Linq

<h2>Create Employee</h2>

<!--Form for adding employee-->
@using (Html.BeginForm(
			actionName: nameof(EmployeeController.Create),
			controllerName: Html.ViewContext.RouteData.Values["controller"].ToString(),
			FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<!-- Employee's first name -->
	<div class="row">
		<div class="col">
			@Html.LabelFor(model => model.FirstName, new { @class = "form-label m-2" })
			@Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
		</div>

		<!-- Employee's last name -->
		<div class="col">
			@Html.LabelFor(model => model.LastName, new { @class = "form-label m-2" })
			@Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
		</div>
	</div>

	//Position
	<div class="form-group">
		@Html.LabelFor(model => model.Post, new { @class = "form-label m-2" })
		@Html.DropDownListFor(model => model.Post,
				Html.GetEnumSelectList<Post>(),
				null,
				new { @class = "form-select" })
	</div>

	//Eployee's skills
	<div class="form-group">
		@Html.LabelFor(model => model.Skills, new { @class = "form-label m-2" })
		@Html.TextAreaFor(model => model.Skills, new { @class = "form-control" })
	</div>

	//submit button
	<div class="form-group">
		<input type="submit" value="Create" class="btn btn-success m-2" />
	</div>

}

Homework 2/HelpDesk/Views/Employee/Delete.cshtml
@model HelpDesk.Models.EmployeeViewModel
@using HelpDesk.Controllers
@using HelpDesk.Enums
@using System.Linq

@using (Html.BeginForm(
							actionName: nameof(EmployeeController.Delete),
							controllerName: Html.ViewContext.RouteData.Values["controller"].ToString(),
							FormMethod.Post))
{

	<div class="card" style="width: 50rem;">
		<div class="card-body">
			<h4 class="card-title">Are you sure you want to delete this?</h4>
			<h5 class="card-subtitle"><u>Employee's Details</u></h5>
			<p class="card-text">@nameof(Model.Id) : @Model.Id</p>
			<p class="card-text">@nameof(Model.FullName) : @Model.FullName</p>
			<p class="card-text">@nameof(Model.Post) : @Model.Post</p>
			<p class="card-text">@nameof(Model.Skills) : @Model.Skills</p>
			<a href="@Url.Action(nameof(EmployeeController.Index))" class="card-link">Back to list</a>
			<!--submit button-->
			<div>
				<input type="submit" value="Delete" class="btn btn-success m-2" />
			</div>
		</div>
	</div>

}

Homework 2/HelpDesk/Views/Employee/Details.cshtml
@model HelpDesk.Models.EmployeeViewModel
@using HelpDesk.Controllers
@using HelpDesk.Enums
@using System.Linq

<div class="card" style="width: 50rem;">
	<div class="card-body">
		<h4 class="card-title"><u>Employee's Details</u></h4>
		<p class="card-text">@nameof(Model.Id) : @Model.Id</p>
		<p class="card-text">@nameof(Model.FullName) : @Model.FullName</p>
		<p class="card-text">@nameof(Model.Post) : @Model.Post</p>
		<p class="card-text">@nameof(Model.Skills) : @Model.Skills</p>
		<a href="@Url.Action(nameof(EmployeeController.Index))" class="card-link">Back to list</a>
	</div>
</div>

Homework 2/HelpDesk/Views/Employee/Edit.cshtml
@model HelpDesk.Models.EmployeeViewModel
@using HelpDesk.Controllers
@using HelpDesk.Enums
@using System.Linq

<h2>Edit Employee</h2>

<!--Form for adding employee-->
@using (Html.BeginForm(
					actionName: nameof(EmployeeController.Edit),
					controllerName: Html.ViewContext.RouteData.Values["controller"].ToString(),
					FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<!-- Employee's first name -->
	<div class="row">
		<div class="col">
			@Html.LabelFor(model => model.FirstName, new { @class = "form-label m-2" })
			@Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
		</div>

		<!-- Employee's last name -->
		<div class="col">
			@Html.LabelFor(model => model.LastName, new { @class = "form-label m-2" })
			@Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
		</div>
	</div>

	//Position
	<div class="form-group">
		@Html.LabelFor(model => model.Post, new { @class = "form-label m-2" })
		@Html.DropDownListFor(model => model.Post,
				Html.GetEnumSelectList<Post>(),
				null,
				new { @class = "form-select" })
	</div>

	//Eployee's skills
	<div class="form-group">
		@Html.LabelFor(model => model.Skills, new { @class = "form-label m-2" })
		@Html.TextAreaFor(model => model.Skills, new { @class = "form-control" })
	</div>

	//submit button
	<div class="form-group">
		<input type="submit" value="Edit" class="btn btn-success m-2" />
	</div>
	<div class="form-group">
		<a href="@Url.Action(nameof(EmployeeController.Index))" class="card-link">Back to list</a>
	</div>

}

Homework 2/HelpDesk/Views/Employee/Index.cshtml
@using HelpDesk.Controllers
@model List<EmployeeViewModel>;

<table class="table">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">FullName</th>
			<th scope="col">Post</th>
			<th scope="col">Skills</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var m in Model)
		{
			<tr>
				<td>@m.Id</td>
				<td>@m.FullName</td>
				<td>@m.Post</td>
				<td>@m.Skills</td>
				<td><a href="@Url.Action(nameof(EmployeeController.Details), new {id = m.Id})">@nameof(EmployeeController.Details)</a></td>
				<td><a href="@Url.Action(nameof(EmployeeController.Edit), new {id = m.Id})">@nameof(EmployeeController.Edit)</a></td>
				<td><a href="@Url.Action(nameof(EmployeeController.Delete), new {id = m.Id})">@nameof(EmployeeController.Delete)</a></td>
			</tr>
		}
	</tbody>
</table>

<div style="display:block">
	<a href="@Url.Action(nameof(EmployeeController.Create))"> Add Employee </a>
</div>

Homework 2/HelpDesk/Views/Home/Index.cshtml
@using HelpDesk.Controllers
@{
    //ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a href="@Url.Action(nameof(EmployeeController.Index), "Employee")"><p>Employee<p></a>
</div>