Course project/HelpDesk_MVC/Controllers/HomeController.cs
using HelpDesk_DomainModel.Models.Identity;
using HelpDesk_MVC.Models;
using HelpDesk_MVC.RequestFilters;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;

namespace HelpDesk_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

			if (User.Identity.IsAuthenticated)
            {
                var actualRole = User.Claims.FirstOrDefault(cl => cl.Type == "ActualRole").Value.ToString() ?? null;

                if (actualRole == UserRoleEnum.Administrator.ToString())
                {
                    return RedirectToAction("AdminPanel");

                }
                if (actualRole == UserRoleEnum.Manager.ToString())
                {
                    return RedirectToAction("ManagerPanel");

                }
                if (actualRole == UserRoleEnum.Employee.ToString())
                {
                    return RedirectToAction("EmployeePanel");

                }
				if (actualRole == UserRoleEnum.Customer.ToString())
				{
					return RedirectToAction("CustomerPage");

				}
				return View();
			}

            return View();
        }

        [RoleBasedAuthorizationFilter(Role = UserRoleEnum.Administrator)]
        public IActionResult AdminPanel()
        {
            return View();
        }

        [RoleBasedAuthorizationFilter(Role = UserRoleEnum.Manager)]
        public IActionResult ManagerPanel()
        {
            return View();
        }

        [RoleBasedAuthorizationFilter(Role = UserRoleEnum.Customer)]
        public IActionResult CustomerPage()
        {
            return View();
        }

        [RoleBasedAuthorizationFilter(Role = UserRoleEnum.Employee)]
        public IActionResult EmployeePanel()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Course project/HelpDesk_MVC/Controllers/OrderController.cs
using HelpDesk_BLL.Contracts;
using HelpDesk_BLL.Contracts.Identity;
using HelpDesk_DomainModel.Models.ECommerce;
using HelpDesk_DomainModel.Models.Identity;
using HelpDesk_MVC.RequestFilters;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;
using static System.Runtime.InteropServices.JavaScript.JSType;
using ILogger = Serilog.ILogger;



namespace HelpDesk_MVC.Controllers
{
	public class OrderController : Controller
	{
		private readonly IOrderService _orderService;
		private readonly UserManager<User> _userManager;
		private readonly ILogger _logger;

		public OrderController(
			IOrderService orderService,
			UserManager<User> userManager,
			ILogger logger
			)
		{
			_orderService = orderService;
			_userManager = userManager;
			_logger = logger;
		}

        [RoleBasedAuthorizationFilter(Role = UserRoleEnum.Customer)]
        public async Task<IActionResult> List(int page = 0)
		{
			var allOrders = new List<OrderBriefModel>();
			var orders = new List<OrderBriefModel>();

            if (User.Identity.IsAuthenticated)
			{
				const int PageSize = 3;
				var currentUser = HttpContext.User;
				var userIdClaim = currentUser.Claims.FirstOrDefault(cl => cl.Type == ClaimTypes.NameIdentifier);
                var actualRole = User.Claims.FirstOrDefault(cl => cl.Type == "ActualRole").Value.ToString();
				if (actualRole == UserRoleEnum.Customer.ToString())
				{
					allOrders = await _orderService.FetchOrders(searchString: userIdClaim.Value.ToString());
					orders = await _orderService.FetchOrders(skip: (page * PageSize), take: PageSize, searchString: userIdClaim.Value.ToString());
				}
				else
				{
                    allOrders = await _orderService.FetchOrders();
                    orders = await _orderService.FetchOrders(skip: (page * PageSize), take: PageSize);
                }
                var count = allOrders.Count;
				ViewBag.MaxPage = (count / PageSize) - (count % PageSize == 0 ? 1 : 0);

				ViewBag.Page = page;

				return View(orders);
			}
			return NotFound("Please, sign in to leave an order!");
		}

        public async Task<IActionResult> ListForManager(int page = 0)
		{
			var allOrders = new List<OrderBriefModel>();
			var orders = new List<OrderBriefModel>();

            if (User.Identity.IsAuthenticated)
			{
				const int PageSize = 3;
				var currentUser = HttpContext.User;
				var userIdClaim = currentUser.Claims.FirstOrDefault(cl => cl.Type == ClaimTypes.NameIdentifier);
                var actualRole = User.Claims.FirstOrDefault(cl => cl.Type == "ActualRole").Value.ToString();
				if (actualRole == UserRoleEnum.Manager.ToString() || actualRole == UserRoleEnum.Administrator.ToString())
				{
                    allOrders = await _orderService.FetchOrders();
                    orders = await _orderService.FetchOrders(skip: (page * PageSize), take: PageSize);
                }
                var count = allOrders.Count;
				ViewBag.MaxPage = (count / PageSize) - (count % PageSize == 0 ? 1 : 0);

				ViewBag.Page = page;

				return View(orders);
			}
			return NotFound("Please, sign in to leave an order!");
		}

        [RoleBasedAuthorizationFilter(Role = UserRoleEnum.Employee)]
        public async Task<IActionResult> ListForEmployee(int page = 0)
        {
            var allOrders = new List<OrderBriefModel>();
            var orders = new List<OrderBriefModel>();

            if (User.Identity.IsAuthenticated)
            {
                const int PageSize = 3;
                var currentUser = HttpContext.User;
                var userIdClaim = currentUser.Claims.FirstOrDefault(cl => cl.Type == ClaimTypes.NameIdentifier);
                var actualRole = User.Claims.FirstOrDefault(cl => cl.Type == "ActualRole").Value.ToString();
                if (actualRole == UserRoleEnum.Employee.ToString())
                {
                    allOrders = await _orderService.FetchOrdersForEmployee();
                    orders = await _orderService.FetchOrdersForEmployee(skip: (page * PageSize), take: PageSize);
                }
                var count = allOrders.Count;
                ViewBag.MaxPage = (count / PageSize) - (count % PageSize == 0 ? 1 : 0);

                ViewBag.Page = page;

                return View(orders);
            }
            return NotFound("Please, sign in to leave an order!");
        }

        public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(OrderDTO order)
		{
			if (User.Identity.IsAuthenticated)
			{
				var currentUser = HttpContext.User;
				var userIdClaim = currentUser.Claims.FirstOrDefault(cl => cl.Type == ClaimTypes.NameIdentifier);
				var user = await _userManager.FindByIdAsync(userIdClaim.Value);

				var newOrderModel = new OrderBriefModel
				{
					User = user,
					OrderText = order.OrderText,
					Date = DateTime.Now,
					Address = order.Address,
					Phone = order.Phone,
					Status = OrderStatusEnum.Placed,
					MinCost = order.MinCost,
					MaxCost = order.MaxCost,
				};

				try
				{
					//Validation on Creating
					if (!ModelState.IsValid)
					{
						return View();
					}
					_orderService.CreateOrder(newOrderModel);
					return RedirectToAction(nameof(List));
				}
				catch
				{
					return View();
				}
			}
			return NotFound("Please, sign in to leave an order!");
		}


		// GET: EmployeeController/Details/5
		public ActionResult Details(long? id)
		{
			if (!id.HasValue)
			{
				return NotFound("Empty id supplied!");
			}

			try
			{
				var order = _orderService.GetOrderById(id.Value);
				return View(order);
			}
			catch
			{
				return NotFound("No such record found!");
			}
		}

		public async Task<IActionResult> Edit(long? id)
		{
			if (!id.HasValue)
			{
				return NotFound("Empty id supplied!");
			}

			try
			{
				//Validation on Editing
				if (!ModelState.IsValid)
				{
					return View();
				}
				var editedOrder = await _orderService.GetOrderById(id.Value);
				return View(editedOrder);
			}
			catch
			{
				return NotFound("No such record found!");
			}
		}

		// POST: EmployeeController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(OrderBriefModel order)
		{

			try
			{
				//Validation on Editing
				if (!ModelState.IsValid)
				{
					return View();
				}
				await _orderService.WriteOrder(order);
				return RedirectToAction(nameof(List));
			}
			catch
			{
				return RedirectToAction(nameof(Index));
			}
		}

		// GET: EmployeeController/Delete/5
		[HttpGet]
		public ActionResult Delete(long? id)
		{
			if (!id.HasValue)
			{
				return NotFound("Empty id supplied!");
			}
			try
			{
				var deletedOrder = _orderService.GetOrderById(id.Value);

				return View(deletedOrder);
			}
			catch
			{
				return NotFound("No such record found!");
			}
		}

		// POST: EmployeeController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(long id)
		{
			try
			{
				_orderService.DeleteOrder(id);
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return NotFound("No such record found!");
			}
		}

	}
}

Course project/HelpDesk_MVC/Views/Home/AdminPanel.cshtml
@using HelpDesk_MVC.Controllers
@using HelpDesk_MVC.Controllers.Identity
@using System.Security.Claims
@{
    //ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Admin Panel</h1>
    <a href="@Url.Action(nameof(UserController.List), "User")"><p>Users List<p></a>
    <a href="@Url.Action(nameof(UserController.EmployeeList), "User")"><p>Employee List<p></a>
    <a href="@Url.Action(nameof(OrderController.ListForManager), "Order")"><p>Orders List<p></a>
    <a href="@Url.Action(nameof(HomeController.Index), "Home")"><p>About Us<p></a>


</div>

Course project/HelpDesk_MVC/Views/Home/CustomerPage.cshtml
@using HelpDesk_MVC.Controllers
@using HelpDesk_MVC.Controllers.Identity
@using System.Security.Claims
@{
    //ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Help Desk portal!</h1>

    <a href="@Url.Action(nameof(OrderController.Create), "Order")"><p>Create Order<p></a>
    <a href="@Url.Action(nameof(OrderController.List), "Order")"><p>Your Orders<p></a>
    <a href="@Url.Action(nameof(HomeController.Index), "Home")"><p>About Us<p></a>


</div>

Course project/HelpDesk_MVC/Views/Home/EmployeePanel.cshtml
@using HelpDesk_MVC.Controllers
@using HelpDesk_MVC.Controllers.Identity
@using System.Security.Claims
@{
    //ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Employee Panel</h1>
    <a href="@Url.Action(nameof(OrderController.ListForEmployee), "Order")"><p>Orders List<p></a>
    <a href="@Url.Action(nameof(HomeController.Index), "Home")"><p>About Us<p></a>


</div>

Course project/HelpDesk_MVC/Views/Home/Index.cshtml
@using HelpDesk_MVC.Controllers
@using HelpDesk_MVC.Controllers.Identity
@using System.Security.Claims
@{
    //ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Help Desk portal!</h1>

        <p>Please, <a asp-controller="Login" asp-action="Index">Sign in</a> or <a asp-controller="User" asp-action="Register">Register</a> to leave an Order.<p>
    <a href="@Url.Action(nameof(HomeController.Index), "Home")"><p>About Us<p></a>


</div>

Course project/HelpDesk_MVC/Views/Home/ManagerPanel.cshtml
@using HelpDesk_MVC.Controllers
@using HelpDesk_MVC.Controllers.Identity
@using System.Security.Claims
@{
    //ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Manager Panel</h1>
    <a href="@Url.Action(nameof(OrderController.ListForManager), "Order")"><p>Orders List<p></a>
    <a href="@Url.Action(nameof(HomeController.Index), "Home")"><p>About Us<p></a>


</div>